# Generated by Django 5.2.4 on 2025-07-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actif'),
        ),
    ]
