# Generated by Django 5.2.4 on 2025-07-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_pdfdocument_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
