# Generated by Django 5.2.4 on 2026-01-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la pub')),
                ('description', models.TextField(verbose_name='Description du produit/service')),
                ('content', models.TextField(blank=True, help_text='Contenu HTML additionnel', verbose_name='Contenu personnalisé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Image publicitaire')),
                ('link_url', models.URLField(blank=True, verbose_name='Lien vers le produit')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Contact (Tel/Email)')),
                ('ad_type', models.CharField(choices=[('popup', 'Pop-up'), ('notification', 'Notification'), ('banner', 'Bannière')], default='notification', max_length=20, verbose_name='Type de pub')),
                ('trigger_action', models.CharField(choices=[('on_load', 'Au chargement de la page'), ('on_download', 'Au téléchargement'), ('on_upload', "À l'envoi d'un document"), ('on_scroll', 'Au défilement')], default='on_load', max_length=20, verbose_name='Déclencheur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-created_at'],
            },
        ),
    ]
