# Generated by Django 5.2.4 on 2026-01-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.IntegerField(default=5, help_text="Durée d'affichage en secondes (pour les popups/notifs auto-fermantes)", verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='trigger_action',
            field=models.CharField(choices=[('on_load', 'Au chargement de la page'), ('on_download', 'Au téléchargement'), ('on_upload', "À l'envoi d'un document"), ('on_scroll', 'Au défilement'), ('on_timer', 'Basé sur le temps (périodique)')], default='on_load', max_length=20, verbose_name='Déclencheur'),
        ),
    ]
