# Generated by Django 5.2.4 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_adinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='study_level',
            field=models.CharField(blank=True, choices=[('Primaire', 'Primaire'), ('Collège/Lycée', 'Collège/Lycée'), ('Secondaire', 'Secondaire'), ('Université', 'Université')], default='', max_length=32, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='study_sublevel',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Sous-niveau'),
        ),
    ]

