# Generated by Django 5.2.4 on 2026-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion


def _seed_levels(apps, schema_editor):
    StudyLevel = apps.get_model("courses", "StudyLevel")
    StudySubLevel = apps.get_model("courses", "StudySubLevel")

    levels = [
        ("primaire", "Primaire", ["CP", "CE1", "CE2", "CM1", "CM2"]),
        ("college_lycee", "Collège/Lycée", ["6ème", "5ème", "4ème", "3ème"]),
        ("secondaire", "Secondaire", ["Seconde", "Première", "Terminale"]),
        ("universite", "Université", ["Licence 1", "Licence 2", "Licence 3", "Master", "Doctorat"]),
    ]

    # Create levels + sublevels
    for level_order, (level_key, level_name, sublevels) in enumerate(levels):
        level_obj, _ = StudyLevel.objects.get_or_create(
            key=level_key,
            defaults={"name": level_name, "order": level_order},
        )
        # Keep name/order in sync if db already exists
        updates = {}
        if level_obj.name != level_name:
            updates["name"] = level_name
        if level_obj.order != level_order:
            updates["order"] = level_order
        if updates:
            StudyLevel.objects.filter(pk=level_obj.pk).update(**updates)
            level_obj.refresh_from_db()

        for sub_order, sub_name in enumerate(sublevels):
            sub_key = (
                sub_name.lower()
                .replace(" ", "_")
                .replace("è", "e")
                .replace("é", "e")
                .replace("ê", "e")
                .replace("à", "a")
                .replace("ç", "c")
                .replace("’", "")
                .replace("'", "")
            )
            StudySubLevel.objects.get_or_create(
                level=level_obj,
                key=sub_key,
                defaults={"name": sub_name, "order": sub_order},
            )


def _migrate_documents(apps, schema_editor):
    PDFDocument = apps.get_model("courses", "PDFDocument")
    StudyLevel = apps.get_model("courses", "StudyLevel")
    StudySubLevel = apps.get_model("courses", "StudySubLevel")

    level_name_to_key = {
        "Primaire": "primaire",
        "Collège/Lycée": "college_lycee",
        "Secondaire": "secondaire",
        "Université": "universite",
    }

    for doc in PDFDocument.objects.all().only("id", "study_level", "study_sublevel"):
        level_name = (doc.study_level or "").strip()
        sub_name = (doc.study_sublevel or "").strip()
        if not level_name or not sub_name:
            continue

        level_key = level_name_to_key.get(level_name)
        if not level_key:
            continue

        try:
            level_obj = StudyLevel.objects.get(key=level_key)
        except StudyLevel.DoesNotExist:
            continue

        # Try to match sublevel by name first
        sub_obj = StudySubLevel.objects.filter(level=level_obj, name=sub_name).first()
        if not sub_obj:
            continue

        PDFDocument.objects.filter(pk=doc.pk).update(study_sublevel_fk=sub_obj)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_pdfdocument_study_level_and_sublevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=64, unique=True, verbose_name="Clé")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Niveau d'étude",
                "verbose_name_plural": "Niveaux d'étude",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudySubLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=64, verbose_name="Clé")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "level",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sublevels", to="courses.studylevel"),
                ),
            ],
            options={
                "verbose_name": "Sous-niveau",
                "verbose_name_plural": "Sous-niveaux",
                "ordering": ["level__order", "order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="studysublevel",
            constraint=models.UniqueConstraint(fields=("level", "key"), name="uniq_sublevel_level_key"),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="study_sublevel_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="courses.studysublevel",
                verbose_name="Sous-niveau",
            ),
        ),
        migrations.RunPython(_seed_levels, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(_migrate_documents, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name="pdfdocument", name="study_level"),
        migrations.RemoveField(model_name="pdfdocument", name="study_sublevel"),
        migrations.RenameField(model_name="pdfdocument", old_name="study_sublevel_fk", new_name="study_sublevel"),
    ]

