# Generated by Django 5.2.4 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_study_levels_and_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=64, unique=True, verbose_name="Clé")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="documents", to="courses.tag", verbose_name="Tags"),
        ),
    ]

