# Generated by Django 5.2.4 on 2026-04-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["name"], "verbose_name": "Domaine", "verbose_name_plural": "Domaines"},
        ),
    ]

