# Generated by Django 5.2.4 on 2026-04-06 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=16)),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='Prix (centimes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('daily_requests_limit', models.PositiveIntegerField(default=500, verbose_name='Limite requêtes/jour')),
                ('daily_download_limit', models.PositiveIntegerField(default=50, verbose_name='Limite téléchargements/jour')),
                ('max_page_size', models.PositiveIntegerField(default=100, verbose_name='Taille max page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre API',
                'verbose_name_plural': 'Offres API',
                'ordering': ['price_cents', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom')),
                ('prefix', models.CharField(db_index=True, max_length=32, verbose_name='Préfixe')),
                ('key_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash (sha256)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clé API',
                'verbose_name_plural': 'Clés API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='courses.apikey')),
            ],
            options={
                'verbose_name': 'Usage API (jour)',
                'verbose_name_plural': 'Usages API (jour)',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='courses.apiplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement API',
                'verbose_name_plural': 'Abonnements API',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(fields=('prefix', 'key_hash'), name='uniq_api_key_prefix_hash'),
        ),
        migrations.AddConstraint(
            model_name='apiusagedaily',
            constraint=models.UniqueConstraint(fields=('api_key', 'date'), name='uniq_api_key_date'),
        ),
    ]
