# Generated by Django 5.2.4 on 2026-04-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_apiplan_apikey_apiusagedaily_usersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocumentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.JSONField(blank=True, default=list)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_mtime', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_cache', to='courses.pdfdocument')),
            ],
            options={
                'verbose_name': 'Texte PDF (cache)',
                'verbose_name_plural': 'Textes PDF (cache)',
            },
        ),
    ]
